name: Data Crawl and Package

on:
  workflow_dispatch:

jobs:
  crawl_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: pip install uv

    - name: Create and activate virtual environment
      run: |
        uv venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Install project in editable mode
      run: |
        source .venv/bin/activate
        uv pip install -e .

    - name: Run data crawling script
      run: |
        source .venv/bin/activate
        .venv/bin/python -m steam_tracker.cli

    - name: Archive output files
      run: |
        zip -r output_data.zip ./output

    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: crawled-data
        path: output_data.zip
